version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_YandexBackendSchool
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - dev.env

  backend:
    build: ./backend
    container_name: backend
    command: bash entrypoint.sh
    volumes:
      - ./backend/apps/shop/migrations:/backend/apps/shop/migrations
      - ./backend/static/:/backend/static/
    ports:
      - 8000:8000
    networks:
      - default
    env_file:
      - backend/dev.env
    restart: always
    depends_on:
      - db

  nginx:
    build: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./backend/static:/backend/static
    depends_on:
      - backend
volumes:
  postgres_data:



